# Generated by Django 5.2.1 on 2025-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_bench', '0002_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_files/'),
        ),
    ]
