# Generated by Django 5.2.1 on 2025-06-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFDFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PFDRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='e.g., o3-2025-04-16, Gemini', max_length=100)),
                ('prompt_system', models.IntegerField(help_text='System prompt version number')),
                ('prompt_user', models.IntegerField(help_text='User prompt version number')),
                ('parameters', models.CharField(help_text='e.g., reasoning effort: medium', max_length=200)),
                ('response_id', models.CharField(blank=True, max_length=100)),
                ('llm_output_markdown', models.TextField(help_text='Original LLM response - paste here')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output_text', models.IntegerField(default=0)),
                ('tokens_output_reasoning', models.IntegerField(default=0)),
                ('true_positives', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('true_negatives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('text_style_score', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('comments_markdown', models.TextField(blank=True, help_text='Your analysis and comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_runs', to=settings.AUTH_USER_MODEL)),
                ('pfd_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pfd_analyzer.pfdfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
