# Generated by Django 5.2.1 on 2025-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfdrun',
            name='prompt_system',
            field=models.CharField(help_text='System prompt version (e.g., 2a, 3_worker)', max_length=50),
        ),
        migrations.AlterField(
            model_name='pfdrun',
            name='prompt_user',
            field=models.CharField(help_text='User prompt version (e.g., 2b, 4_final)', max_length=50),
        ),
    ]
