# Generated by Django 5.2.1 on 2025-06-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_analyzer', '0002_alter_pfdrun_prompt_system_alter_pfdrun_prompt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfdrun',
            name='name',
            field=models.CharField(blank=True, help_text='Optional descriptive name for this run (defaults to run number if empty)', max_length=255),
        ),
        migrations.AddField(
            model_name='pfdrun',
            name='related_run',
            field=models.ForeignKey(blank=True, help_text='Connect this run to another run it depends on or builds upon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_runs', to='pfd_analyzer.pfdrun'),
        ),
        migrations.AddField(
            model_name='pfdrun',
            name='relationship_description',
            field=models.TextField(blank=True, help_text="Describe how this run relates to the connected run (e.g., 'Used the outcome of run #23 as input for this analysis')"),
        ),
    ]
